
#
# Environment variables for Apache Hadoop 3.x.x + Spark 3.x.x
#
export HADOOP_HOME="/root/hadoop"
export HADOOP_COMMON_HOME="${HADOOP_HOME}"
export HADOOP_HDFS_HOME="${HADOOP_HOME}"
export HADOOP_MAPRED_HOME="${HADOOP_HOME}"
export HADOOP_YARN_HOME="${HADOOP_HOME}"
export HADOOP_CONF_DIR="${HADOOP_HOME}/etc/hadoop"
export HADOOP_COMMON_LIB_NATIVE_DIR="${HADOOP_HOME}/lib/native"
export HADOOP_OPTS="$HADOOP_OPTS -XX:-PrintWarnings -Djava.net.preferIPv4Stack=true -Djava.library.path=${HADOOP_COMMON_LIB_NATIVE_DIR}"
export LD_LIBRARY_PATH="${HADOOP_COMMON_LIB_NATIVE_DIR}"
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64/jre/"
#export _JAVA_OPTIONS="-Xmx2048m"
export HDFS_NAMENODE_USER="root"
export HDFS_DATANODE_USER="${HDFS_NAMENODE_USER}"
export HDFS_SECONDARYNAMENODE_USER="${HDFS_NAMENODE_USER}"
export YARN_RESOURCEMANAGER_USER="${HDFS_NAMENODE_USER}"
export YARN_NODEMANAGER_USER="${HDFS_NAMENODE_USER}"
export SPARK_HOME="${HADOOP_HOME}/spark"
export PATH="$PATH:${HADOOP_HOME}/sbin:${HADOOP_HOME}/bin:${JAVA_HOME}/bin:${SPARK_HOME}/bin:${SPARK_HOME}/sbin"
